[package]
name = "fork-simulator"
version = "0.1.0"
authors = ["Jeremiah Wagstaff <jeremiah.wagstaff@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "0.16.9"
bitintr = "0.3.0"
s-tree = "0.1.0"
